-- ============================================================
-- 08 — Validation / Debug Queries
-- ============================================================
SHOW TASKS IN SCHEMA OBM_DEV_OBM.INT;

SELECT NAME, STATE, ERROR_MESSAGE, SCHEDULED_TIME, COMPLETED_TIME
FROM TABLE(OBM_DEV_OBM.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'LOAD_ALL_CLEAN_TASK',
    SCHEDULED_TIME_RANGE_START => DATEADD('HOUR', -2, CURRENT_TIMESTAMP())
))
ORDER BY SCHEDULED_TIME DESC;

SELECT COUNT(*) FROM OBM_DEV_OBM.RAW.ORDERS_RAW_JSON;
SELECT * FROM OBM_DEV_OBM.RAW.ORDERS_RAW_JSON_STREAM;
SELECT * FROM OBM_DEV_OBM.RAW.ORDERS_BATCH_STAGING;
SELECT * FROM OBM_DEV_OBM.INT.ORDERS ORDER BY order_id;
SELECT * FROM OBM_DEV_OBM.INT.CUSTOMERS ORDER BY customer_id;
SELECT * FROM OBM_DEV_OBM.INT.ORDER_ITEMS ORDER BY order_id, item_id;
SELECT * FROM OBM_DEV_OBM.RAW.REJECTED_RECORDS ORDER BY rejected_at DESC;
